### ISSUE TITLE
Non-Mac Keyboard + Mouse

### ISSUE THREAD

**Issue by SeaDaddytheRed** [ruundii/bthidhub#16]
Hello, First thank you for this idea.  It is exactly what I have been looking for to solve my multiple computers/one keyboard mouse setup.

I am having some problems though.

1. I am using a non-Mac keyboard, 87 key US, and I don't know the shortcut to switch connected devices.
2. No matter what mouse I connect to the pi it shows up as a mouse in the drop down menu of your program but it doesn't work at all on the computer.  I have tried wireless logitech, and my Anker gaming mouse, neither work.
Thanks again for this great idea.  I hope I can get it working!

**Comment by Dreamsorcerer** [comment]
Same issue here, the filter removes all 8 byte commands:
https://github.com/ruundii/bthidhub/blob/master/mouse_message_filter.py#L10

These include all the movement events of a mouse...

I commented out those lines and the mouse works, however the vertical axis is 10x more sensitive than the horizontal axis. The result is that moving the mouse up/down is only just usable at the lowest sensitivity, while move left/right results in the cursor jumping up/down as it moves along because it picks up every little movement on that axis.

**Comment by Dreamsorcerer** [comment]
@ruundii Do you have any advise on how to debug these issues? I can see a couple of things that stand out, but not sure how to actually change them.

For example:

- bthidhub has the X/Y logical minimum/maximum reported as -2047/2047, while my mouse connected to it reports -32768/32768.
- The events from the mouse on the rpi begin with `8 00`, but the events from bthidhub begin with `9 03`.

But, I have no idea how to change the values sent initially.
I've also tried changing the prefix in MouseMessageFilter, but this just results in the events not getting sent at all.

**Comment by Dreamsorcerer** [comment]
OK, I managed to update the sdp_record.xml, at which point the mouse works properly. I don't think there is a "standard" mouse config you can provide in the sdp record, so it would be better to look at dynamically creating one.

**Comment by Dreamsorcerer** [comment]
Let's track this in #23, which should resolve the issue.
I've described a workaround here: https://github.com/ruundii/bthidhub/issues/11#issuecomment-841819628
